name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  packages: write
  contents: write
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Set up protoc
        uses: arduino/setup-protoc@v3

      - name: Build Rust project
        run: cargo build --release

      - name: Build Java project
        working-directory: bridge
        run: ./gradlew build

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/minecraftd,target/release/mcctl,bridge/dist/*.jar"
