name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  packages: write
  contents: write
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"

      - name: Build Rust project
        run: cargo build --release

      - name: Build Java project
        working-directory: bridge
        run: ./gradlew build

      - name: Create GitHub Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
